### ISSUE TITLE
No fatal log level

### ISSUE THREAD

**Issue by molynerd** [stackify/stackify-log-nodejs#18]
We used to have this log level in the C# version of the logger (using log4net) and when using the winston transport for nodejs. This seems to be missing here and is critical for our environment.

If acceptable. I'd like to get this feature added.

**Comment by molynerd** [comment]
went ahead and PR'd it. let me know your thoughts.

**Comment by darinhoward** [comment]
@molynerd  I'll review - should be able to merge and publish tomorrow. Thanks for the pull request.
