### ISSUE TITLE
High severity vulnerability issue with sync-request > then-request > qs

### ISSUE THREAD

**Issue by traceygibbons** [stackify/stackify-log-nodejs#28]
See: https://npmjs.com/advisories/1469

Presumably due to the old version of https://www.npmjs.com/package/sync-request - also not intended for production use?

**Comment by darinhoward** [comment]
updating dependency version in commit - 90987b649da8194ecf1359189baf07d11a174cb9

**Comment by darinhoward** [comment]
Fix is in version https://www.npmjs.com/package/stackify-logger/v/3.0.9 . Thank you for reporting this issue.

**Comment by traceygibbons** [comment]
> Fix is in version https://www.npmjs.com/package/stackify-logger/v/3.0.9 . Thank you for reporting this issue.

You're welcome, thanks for the speedy fix!
